### ISSUE TITLE
metadata error

### ISSUE THREAD

**Issue by RyanConway91** [pymt-lab/pymt_prms_surface#10]
When I run:
```
from pymt.models import PRMSSurface, PRMSSoil
psrf = PRMSSurface()
```
The second line causes the following error:
```
Traceback (most recent call last):
  File "/home/chadmin/anaconda3/envs/pymt/lib/python3.10/site-packages/model_metadata/find.py", line 51, in find_metadata_files
    with as_cwd(datadir, create=False):
  File "/home/chadmin/anaconda3/envs/pymt/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/chadmin/anaconda3/envs/pymt/lib/python3.10/site-packages/model_metadata/scripting.py", line 14, in as_cwd
    os.chdir(path)
FileNotFoundError: [Errno 2] No such file or directory: '/home/chadmin/anaconda3/envs/pymt/share/csdms/PRMSSurface'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/api_test/emsdatasets_ipynb_to_py/ModflowPRMS/sagehen-api.py", line 131, in <module>
    msurf = PRMSSurface()
  File "/home/chadmin/anaconda3/envs/pymt/lib/python3.10/site-packages/pymt/framework/bmi_bridge.py", line 153, in __init__
    super(_BmiCap, self).__init__()
  File "/home/chadmin/anaconda3/envs/pymt/lib/python3.10/site-packages/pymt/framework/bmi_timeinterp.py", line 16, in __init__
    super(BmiTimeInterpolator, self).__init__(*args, **kwds)
  File "/home/chadmin/anaconda3/envs/pymt/lib/python3.10/site-packages/pymt/framework/bmi_setup.py", line 19, in __init__
    self._meta = PluginMetadata(self)
  File "/home/chadmin/anaconda3/envs/pymt/lib/python3.10/site-packages/pymt/framework/bmi_metadata.py", line 101, in __init__
    ModelMetadata.__init__(self, path_to_mmd)
  File "/home/chadmin/anaconda3/envs/pymt/lib/python3.10/site-packages/model_metadata/modelmetadata.py", line 64, in __init__
    self._files = find_metadata_files(self._path)
  File "/home/chadmin/anaconda3/envs/pymt/lib/python3.10/site-packages/model_metadata/find.py", line 55, in find_metadata_files
    raise MetadataNotFoundError(datadir)

```

If I look for the path in line 8 of the error (/home/chadmin/anaconda3/envs/pymt/share/), there is indeed no "csdms" folder. Did I miss a download somewhere?

**Comment by rmcd-mscb** [comment]
Ryan - there are a few demo notebooks here: https://github.com/nhm-usgs/bmi-prms-demo.  There is also an environment.yml you can use to create an environment.  Give it a try and perhaps that will help fix the issue you are seeing.

**Comment by RyanConway91** [comment]
That did it, thank you!
